name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: What PHP version are you using?
      placeholder: "8.3"
    validations:
      required: true

  - type: input
    id: laravel-version
    attributes:
      label: Laravel Version
      description: What Laravel version are you using?
      placeholder: "12.x"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Call `Tap::charges()->create([...])`
        2. With this payload: `[...]`
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: php

  - type: textarea
    id: error
    attributes:
      label: Error Message / Stack Trace
      description: If applicable, paste the error message or stack trace
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have verified this is not a Tap API issue
          required: true